### ISSUE TITLE
Scope out MVP for Drupal Open Learning relaunch

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/drupalopenlearning#1]
The new site for Drupal Open Learning will be powered by Open Ulmus/ELMSLN https://github.com/elmsln/openulmus.org/issues/1#issuecomment-331521363

https://docs.google.com/document/d/1ogL5VKRNAfJMfAybztRL2EJ2-Sx3NBsT3ZErNYU1gXY/edit?usp=sharing has a bunch of this throughout but we need a solid 1 paragraph of what this is and why it's useful.

Key For Drupal Open Learning Launch:
- [ ] Budget 
- [ ] Initial Training Defined
- [ ] Roles  
- [x] Social Media Presence 
- [x] Drupal Open Learning Collective Created 
- [ ] Branding Website (Grav)
- [ ] Open Social
- [ ] Initial 'Drupal Open Learning' Training Course Outline
- [ ] Run 3 Dojo Sessions

As a Drupal Open Learning project, we could make defining the scope part of the learning experience. https://github.com/elmsln/openulmus.org/issues/1

**Comment by mmilutinovic013** [comment]
I have added "Add Open Social as Branding Site" here for further discussion. If we want to include this in MVP launch we can -- however -- if we want a quicker launch we can use the Grav method that we did for th Open Ulmus site itself.

**Comment by gusaus** [comment]
Closing out and referencing https://www.drupal.org/node/476030

We'll reference the project scope in the new plan.
