### ISSUE TITLE
Assemble team to develop and maintain the Drupal Open Learning site

### ISSUE THREAD

**Issue by gusaus** [DrupalOpenLearning/drupalopenlearning#2]
We need to identify roles needed to develop, manage and maintain the website. As the site will be powered by Open Ulmus/ELMSLN, the needs should be identical to https://github.com/elmsln/openulmus.org/issues/2

We're defining roles on the wiki - https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Drupal-Open-Learning-Team

- [ ] [Technical Project Manager](https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Team#technical-project-manager) 
- [ ] [Technology Manager/SysAdmin](https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Drupal-Open-Learning-Team#technology-managersysadmin)
- [ ] [Technical Lead / Site Architect](https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Drupal-Open-Learning-Team#technical-lead--site-architect)
- [ ] [Site Builder](https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Drupal-Open-Learning-Team#site-builder) 

What other roles do we need?

**Comment by gusaus** [comment]
As discussed in the Open Ulmus project https://github.com/elmsln/openulmus.org/issues/2#issuecomment-327961621, the project manager role is key. 

@btopro it would be great if you could update PM responisbilites in the wiki https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Team#technical-project-manager or 'once again' describe what this role entails in ELMS world.

If this is the general description of the role https://github.com/elmsln/openulmus.org/issues/2#issuecomment-327961621 that @mmilutinovic1313 is taking on, possibly @btopro and @kat-wehr could be mentors/advisors?

**Comment by gusaus** [comment]
@danielrose28 Are you still interested in the sysadmin role? https://github.com/elmsln/openulmus.org/issues/3#issuecomment-319852391

**Comment by CybersecDan** [comment]
Hey all. I sincerely apologize for missing any communications. I've started a new job with new email so I was missing out on some stuff. Things are pretty hectic for me recently since starting a new job and other personal endeavors. I'm gonna have to take a bit of a break. I apologize for causing any inconvenience.

**Comment by gusaus** [comment]
@danielrose28 No problem - congrats on the new gig. There most likely will be additional opportunities if/when you become available again.

 @mmilutinovic1313 I'd say filling out the [sysadmin role](https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Drupal-Open-Learning-Team#technology-managersysadmin) (mentor & apprentice) is a priority.

**Comment by mmilutinovic013** [comment]
Technology Manager/SysAdmin - @SuperUserNick @scott246 would be good for the apprentice and possibly mentor role as they have a bit of background in AWS. I will ping the drupal open learning slack to see if there are others that could mentor in that role.

**Comment by mmilutinovic013** [comment]
Currently, I am acting as a sysadmin in addition to my other role.

**Comment by gusaus** [comment]
@mmilutinovic1313 Similar to the Project Manager/Instructional Designer https://github.com/DrupalOpenLearning/drupalopenlearning/issues/2#issuecomment-333906351, we should make sure [the wiki](https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Team#technology-managersysadmin) accurately describes the responsibilities, time commitment, and incentives of this role.

We can definitely do some Dojo working sessions on Twitch where we can try to clarify these roles and put the word out. As we were previously discussing for Open Ulmus https://github.com/elmsln/openulmus.org/issues/3#issuecomment-321418581, possibly @djfusco may also be interested on the mentoring/training side?

**Comment by mmilutinovic013** [comment]
@gusaus I don't seem to have access to edit the wiki. I think if @djfusco is interested he would make a great mentor for AWS folks. I am still talking to @SuperUserNick about the apprentice role for AWS related work here and will keep you updated on the progress / any other contacts.

**Comment by gusaus** [comment]
@mmilutinovic1313 You should be able to edit the wiki now. Per https://github.com/DrupalOpenLearning/drupalopenlearning/issues/2#issuecomment-333906351 I think clarifying the PM/ID roles and requirements is still a big one to sort out. I'm going on the assumption that you'd be focusing more on the the PM role as @btopro previously described? https://github.com/elmsln/openulmus.org/issues/2#issuecomment-327961621

> project manager is going to be the biggy. Envisioning what it should provide to the rest of open collective, where there's overlap with dojo, what courses / trainings to pursue. From there, identifying technologies and personnel needed to properly author those courses/trainings.

>This needs a PM who has technical and training space knowledge, having worked with Drupal / other technical communities would be a plus. I'd imagine this could be a part time gig, maybe 5-10 hours a week to get up and going. If needs are identified not provided by the platform or other collectives then getting those functionalities pegged for being worked on in the elmsln/drupal community.

If so, I think https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Team#technical-project-manager would be a seperate role... possibly best to have someone familiar with the cutting edge of ELMS add some specificity to the requirements of this role.

**Comment by mmilutinovic013** [comment]
Oh I saw those as the same role. I might be wrong but I think the PM would define the vision and help assist site builders etc with anything technical?

**Comment by djfusco** [comment]
I can certainly help with AWS and the stack needed to support ELMS.  Just need to know your expectations of the role as well as payment model (for AWS).  I'm at a point with other projects where I can help with the back-end stuff, but not PM stuff.  So, if someone, who's in charge can direct what needs to happen, I'm more likely to be able to help.

**Comment by btopro** [comment]
I'm currently paying for AWS since I was told there might be a chance to get Amazon to pay for it somehow (cheaper then where I was hosting it on my own dime so I don't care)

**Comment by gusaus** [comment]
@djfusco I think what @btopro described in the [google doc](https://docs.google.com/document/d/11g4tAxHIAu_LuTcDPx-9bFcBqBIxKt85KuKJeT1LvDM/edit?usp=sharing) could provide some insight?

>So if it's a SaaS available to other collectives then it's a full stack dev or some combination of time from sys admin (to get it setup mostly that troubleshoot infra tho shouldnt be much especially initially) and a developer to do custom workflows / integrations (for example making sure that when a new collective is registered, that account is hooked into collective and automatically creates spaces or whatever the desire is). I'd say you want time from someone who is 60% drupal, 10% sys ops, 30% front end if this helps you break down what someone should know / how much they do.

>This then would need someone in the collective to run point on features needs assessment / PM type of stuff.

>Now, if you are talking Dojo which is very unique relative to the "make a space for each collective to host some training" then you might be talking a part time instructional designer 1st to make a training on how to use the system for people going through it and then to help with the more collective focused trainings / courses to produce.

If https://github.com/elmsln/openulmus.org/issues/1 is in scope with @mmilutinovic1313's role as PM, then I guess he'll be able to discuss the reqruiments more with the ELMS team and add some detail to https://github.com/DrupalOpenLearning/drupalopenlearning/wiki/Drupal-Open-Learning-Team#technology-managersysadmin

**Comment by mmilutinovic013** [comment]
Hi @djfusco -- That'd be in scope for me. I will reach out to @btopro about what he was saying about Amazon paying. If not I think we need to prioritize a monthly cost coming out of whatever collective this is being funded from. x% goes to hosting/maintaining costs.

There are also two people here that I know that may be interested in learning more about AWS as apprentices. Once I get confirmation from them I was going to say we coordinate a way for them to help maintain, tune, and learn about hosting.

**Comment by ikit-claw** [comment]
I'd be willing to assist I've worked with a lot of hosts but not AWS before.

**Comment by mmilutinovic013** [comment]
@ikit-claw and @djfusco I added you both to the AWS role as advisors. Would either of you be interested in another role on the list, or see a need for another role to be created?

**Comment by gusaus** [comment]
Per https://github.com/elmsln/openulmus.org/issues/2#issuecomment-336574877 I think the mentors/advisors/leads here will be identical to Open Ulmus. I'm going on the assumption that the Drupal Open Learning site would be an instance of Open Ulmus/ELMS. 

If we consider Drupal Open Learning a project of Open Ulmus/ELMS, possibly we can clean up  https://github.com/elmsln/openulmus.org/issues/2 and expand on roles needed to manage and sustain Open Ulmus on the wiki @mmilutinovic1313 will be copying over? 

Each site will have a different set of apprentices or students, so there will be some variation to these issues.

**Comment by mmilutinovic013** [comment]
Agreed. I saw Drupal Open learning as the first "system" running on Open Ulmus. I envisioned Open Ulmus as advertising the different collectives/groups that it provides its services too, as well as offering an option to have courses hosted on Open Ulmus itself (rather than groups needing to install it themselves). This I think is more of a stretch, but I was thinking that could be a future feature.

**Comment by gusaus** [comment]
@mmilutinovic1313 I've assigned you this issue, but we should keep hashing out the roles in https://github.com/elmsln/openulmus.org/issues/2

Also want to reference https://github.com/DrupalOpenLearning/administration/issues/1 which has more to do with sustaining the program.

**Comment by mmilutinovic013** [comment]
@gusaus - perfect. Do I have admin to edit these posts? I need to be able to edit the checklists if possible. For now here is the checklist!

- [x] Technical Project Manager - @mmilutinovic1313
- [x] Technology Manager/SysAdmin - @djfusco 
- [x] Technical Lead / Site Architect - @btopro 
- [ ] Site Builder - NEED Instructional Designer
- [ ] Webmaster - DO NOT NEED

**Comment by mmilutinovic013** [comment]
I think the site builder would be an instructional designer paired with an ELMS:LN expert. if they are the same person that'd be great. We do not need a webmaster per se as the tech manager / sys admin takes over this role I believe.

**Comment by gusaus** [comment]
@mmilutinovic1313 You should now have the ability to edit posts. 

Couple followup questions assuming we're clear on how Drupal Open Learning and Open Ulmus overlap https://github.com/DrupalOpenLearning/drupalopenlearning/issues/2#issuecomment-336584182

Would @djfusco be best suited for the SysAdmin role if it's consistant with we've been discussing in https://github.com/DrupalOpenLearning/drupalopenlearning/issues/2#issuecomment-336220306 https://github.com/DrupalOpenLearning/drupalopenlearning/issues/2#issuecomment-336237002 if we could make that work financially?

Would the Instructional designer paired with an ELMS:LN expert https://github.com/DrupalOpenLearning/drupalopenlearning/issues/2#issuecomment-338541143 head up the production of the accomponiying course https://github.com/elmsln/openulmus.org/issues/14? If so, this would eliminate the need for a paid site builder or webmaster, since we'd be providing knowledge and an actual site for students to gain real world experience. 

Does that make any sense?

**Comment by mmilutinovic013** [comment]
1. Yes, I have listed @djfusco as the Technology Manager if he is still interested in the role.
2. The ID role can be paired with the ELMS:LN expert. The expert can float and would be either or both the Tech Project Manager or Technical Lead. This person can help the ID with the course creation. Someone such as @kat-wehr who knows ELMS:LN as a whole and is an experienced ID would be ideal for this position, as they would be skilled at building the course in the ELMS:LN context immediately.

**Comment by djfusco** [comment]
Yes, I'm good with that @mmilutinovic1313   Just let me know when we'll be getting together to discuss our next steps.

**Comment by mmilutinovic013** [comment]
I hope to have a clear plan by the end of this week and or next that I can relay to you and @kat-wehr. I will keep you in the loop here and on slack! 😄

**Comment by gusaus** [comment]
Closing out and referencing https://www.drupal.org/node/476030

Ideally someone conversing here or in #drupalopenlearning (Drupal Slack) will want to take the lead and create a new plan... based on the old one! 

We'll list out the team (including roles/time commitment/budget) in the new plan.
